rustflags = ["-C", "plt=yes"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.wasm32-wasi]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "target-feature=+avx2,+fma,+avx512f,+avx512bw,+avx512vl"]
rustflags = ["-C", "target-feature=+avx2,+fma"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"